// Generated by https://quicktype.io

export interface UserResponse {
    id_empleado:          number;
    id_autoridad:         number;
    nombre_empleado:      string;
    apellidos_empleado:   string;
    uid_empleado:         string;
    pwd_empleado:         string;
    ultimologin_empleado: string;
    id_estatusempleado:   number;
    vigencia_empleado:    number;
    rpl_empleado:         RplEmpleado;
    caja_empleado:        CajaEmpleado;
    rplnube_empleado:     RplEmpleado;
}

export enum CajaEmpleado {
    N = "N",
}

export enum RplEmpleado {
    R = "R",
    X = "X",
}
